### ISSUE TITLE
Cannot get this xposed module to work on my S5

### ISSUE THREAD

**Issue by peteban** [phillipberndt/ChooseableOutgoingCalls#2]
Hi...
I am trying to resolve the code bug 58097 using your xposed module.
I have a Galaxy S5 G900F with rooted stock ROM Android 4.4.2, Baseband G900FXXU1ANG2, Kernel version 3.4.0-2089850.
The Xposed Framework (2.6.1) is installed and working as far as I know, since I got some other modules to work.
I have tried a few times to uninstall/reinstall but no joy. Your module never asks for Superuser access, but then some of the other working modules also don't ask, so not sure this is significant. I have pasted from the Xposed log the following, seems to show something related to "com.android.phone.PhoneFeature", this seems to not appear when I uninstall your module.
-----------------
18 Jan 2015 15:32:30 UTC
Loading Xposed v54 (for Zygote)...
Running ROM 'KOT49H.G900FXXU1ANG2' with fingerprint 'samsung/kltexx/klte:4.4.2/KOT49H/G900FXXU1ANG2:user/release-keys'
Loading modules from /data/app/com.devortex.TWCallRecorder-1.apk
  Loading class com.devortex.TWCallRecorder.TWCallRecorder
Loading modules from /data/app/com.smartmadsoft.xposed.samsungcameragallery-1.apk
  Loading class com.smartmadsoft.xposed.samsungcameragallery.Selfie
Loading modules from /data/app/com.invano.fingerlock-1.apk
  Loading class com.invano.fingerlock.hook.LockApp
  Loading class com.invano.fingerlock.hook.LockedUninstallerActivity
Loading modules from /data/app/com.whd.wifikeyview-1.apk
  Loading class com.whd.wifikeyview.WiFiKeyView
de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.phone.PhoneFeature
	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:52)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:136)
	at com.devortex.TWCallRecorder.TWCallRecorder.handleLoadPackage(TWCallRecorder.java:33)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34)
	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)
	at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:208)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)
	at android.app.ActivityThread.handleBindApplication(Native Method)
	at android.app.ActivityThread.access$1600(ActivityThread.java:172)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1362)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5586)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: com.android.phone.PhoneFeature
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:251)
	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:50)
	... 19 more
Caused by: java.lang.NoClassDefFoundError: com/android/phone/PhoneFeature
	... 23 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.phone.PhoneFeature" on path: DexPathList[[zip file "/system/framework/twframework.jar", zip file "/system/framework/sechardware.jar", zip file "/system/framework/multiwindow.jar", zip file "/system/framework/libvtmanagerjar.jar", zip file "/system/framework/secmediarecorder.jar", zip file "/system/framework/sec_platform_library.jar", zip file "/system/framework/smatlib.jar", zip file "/system/priv-app/SecTeleService.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:67)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
	... 23 more

**Comment by phillipberndt** [comment]
Bug 58097 and this module concern themselves with Google's contacts app. S5 stock uses a proprietary replacement, which means this module can't be expected to work.

Since I don't run stock on my S5, I won't be able to add support for you, sorry. If you want to add support for Samsung's app yourself, see [this tutorial](https://github.com/rovo89/XposedBridge/wiki/Development-tutorial). It won't be quite as easy as with Google's app, because you don't have the source code available, but with the "Exploring your target and finding a way to modify it" chapter of the tutorial I guess you should be able to find the point where you need to do a similar modification as I do in this module. If you manage to add support and want to share the fix, please open a pull request. I'll merge your changes and will make sure that the module works on either rom then.

**Comment by peteban** [comment]
Hi Philip,

Thanks for your reply, I understand.
Unfortunately, it is most likely beyond me to modify the Samsung app, as I
am not a programmer. I will take a look when I can find some time and if I
get anywhere, I will share with you.

All the best
Pete
